// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"week04/internal/conf"
	"week04/internal/data"
	"week04/internal/server"
	"week04/internal/service"
)

// Injectors from wire.go:

func initApp(confData *conf.Data) *service.Server {
	dbModel := data.NewDBModel(confData)
	serverServer := server.NewServer(dbModel)
	serviceServer := service.New(confData, serverServer)
	return serviceServer
}
